{
 "title": "Large Map - Cases World",
 "tags": [ "dash-1" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "country",
    "label": "country",
    "query": "label_values(confirmed, country)"
   }
  ]
 },
 "panels": [
  {
   "title": "$country - Total \"Confirmed\" ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"$country\"})"
    }
   ]
  },
  {
   "title": "$country - Total \"Deaths\"",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"${country}\"})"
    }
   ]
  },
  {
   "title": "CFR (Fatality Rate)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deaths{country=\"$country\"}) / sum(confirmed{country=\"$country\"}) * 100"
    }
   ]
  },
  {
   "title": "Confirmed Cases By County",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
   "valueName": "current",
   "targets": [
    {
     "expr": "confirmed{country=\"$country\", lat!=\"0.0\"} >0"
    }
   ]
  },
  {
   "title": "Deaths  By County",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 22 },
   "valueName": "current",
   "targets": [
    {
     "expr": "deaths{country=\"$country\", lat!=\"0.0\"} >0"
    }
   ]
  }
 ]
}