{
 "title": "Large Map - Cases by County",
 "tags": [ "dash-1" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "United States - Total \"Confirmed\" ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"})"
    }
   ]
  },
  {
   "title": "United States - Total \"Deaths\"",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"})"
    }
   ]
  },
  {
   "title": "CFR (Fatality Rate)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"}) / sum(confirmed{country=\"US\"}) * 100"
    }
   ]
  },
  {
   "title": "Confirmed Cases By County",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
   "valueName": "current",
   "targets": [
    {
     "expr": "confirmed{country=\"US\", lat!=\"0.0\"} >0"
    }
   ]
  },
  {
   "title": "Deaths  By County",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 22 },
   "valueName": "current",
   "targets": [
    {
     "expr": "deaths{country=\"US\", lat!=\"0.0\"} >0"
    }
   ]
  }
 ]
}