{
 "title": "New dashboard Copy",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": "label_values(confirmed,country)"
   },
   {
    "name": "state",
    "label": "state",
    "query": "label_values(confirmed{country=\"$country\",state!=\"Recovered\" ,state!=\"Grand Princess\",state!=\"Diamond Princess\"},state)"
   },
   {
    "name": "county",
    "label": "county",
    "query": "label_values(confirmed{country=\"$country\",state=~\"$state\"},county)"
   }
  ]
 },
 "panels": [
  {
   "title": "map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Case Confirmed By County",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
     "valueName": "current",
     "targets": [
      { "expr": "confirmed" }
     ]
    },
    {
     "title": "Case deaths By County",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 1 },
     "valueName": "current",
     "targets": [
      {
       "expr": "deaths{country=\"US\", lat!=\"0.0\"} >0"
      }
     ]
    },
    {
     "title": "Death Rate by County",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
     "valueName": "current",
     "targets": [
      {
       "expr": "deaths{country=\"US\"}/confirmed{country=\"US\"}*100>0"
      }
     ]
    },
    {
     "title": "Country Level Confirmed Growth Rate",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(confirmed)by(country)-sum(confirmed offset 1d)by(country) ",
       "legendFormat": "{{country}} "
      }
     ]
    }
   ]
  },
  {
   "title": "country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Country Case Recovered",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sort(sum(recovered)by(country))",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Country Recover rate",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 2 },
     "targets": [
      {
       "expr": "sort(sum(recovered)by(country)/sum(confirmed)by(country))",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "Country Case Recovered",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 0, "y": 11 },
     "targets": [
      { "expr": "sort(sum(deaths)by(country))", "legendFormat": "{{country}}" }
     ]
    },
    {
     "title": "Country Death Rate",
     "type": "table",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
     "targets": [
      {
       "expr": "sort(sum(deaths)by(country)/sum(confirmed)by(country))",
       "legendFormat": "{{country}}"
      }
     ]
    },
    {
     "title": "$country only Recovered Rate ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(recovered{country=~\"$country\"})/sum(confirmed{country=~\"$country\"})",
       "legendFormat": "{{$country}}"
      }
     ]
    },
    {
     "title": "$country only Deaths Rate ",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "sum(deaths{country=~\"$country\"})/sum(confirmed{country=~\"$country\"})",
       "legendFormat": "{{$country}}"
      }
     ]
    },
    {
     "title": "$country only under treatment rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "(sum(confirmed{country=~\"$country\"})-sum(deaths{country=~\"$country\"}))/sum(confirmed{country=~\"$country\"})",
       "legendFormat": "{{$country}}"
      }
     ]
    }
   ]
  },
  { "title": "state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "US deaths case ",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sort(sum(deaths{country=\"US\"})by(state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "US death rate",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sort(sum(deaths{country=\"US\",state!=\"Recovered\"})by(state)/sum(confirmed{country=\"US\",state!=\"Recovered\"})by(state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "US case confirmed",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sort(sum(confirmed{country=\"US\"})by(state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "US under treatment case",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "sort(sum(confirmed{country=\"US\"})by(state)-sum(deaths{country=\"US\"})by(state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "7 days confirmed case trend ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(confirmed{country=\"US\"})by(state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "7 days deaths case trend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(deaths{country=\"US\"})by(state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$state case deaths rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\",state=~\"$state\"})/sum(confirmed{country=\"US\",state=~\"$state\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$state case deaths growth rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(deaths{country=\"US\",state=~\"$state\"})/sum(confirmed{country=\"US\",state=~\"$state\"}))-(sum(deaths{country=\"US\",state=~\"$state\"} offset 1d)/sum(confirmed{country=\"US\",state=~\"$state\"}offset 1d))",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}