{
 "title": "State, County - MAP & Case Data",
 "tags": [ "dash-2" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "state",
    "query": "label_values(confirmed{country=\"US\"}, state)"
   },
   {
    "name": "county",
    "label": "county",
    "query": "label_values(confirmed{country=\"US\", state=\"$state\"}, county)"
   }
  ]
 },
 "panels": [
  { "title": "State Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State CFR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{state=\"$state\"}) / sum(confirmed{state=\"$state\"}) * 100"
    }
   ]
  },
  {
   "title": "County CFR ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\",state=\"$state\",county=\"$county\"}) / sum(confirmed{country=\"US\",state=\"$state\",county=\"$county\"}) * 100"
    }
   ]
  },
  {
   "title": "% Change [1d] - Confirmed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(confirmed{state=\"$state\"} - confirmed{state=\"$state\"} offset 1d) / sum(confirmed{state=\"$state\"}offset 1d) * 100"
    }
   ]
  },
  {
   "title": "% Change[3d] - Confirmed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{county=\"$county\"} - confirmed{county=\"$county\"} offset 3d) / sum(confirmed{county=\"$county\"} offset 3d) * 100"
    }
   ]
  },
  {
   "title": "% Change [1d] - Deaths",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{state=\"$state\",county=\"$county\"} - deaths{state=\"$state\",county=\"$county\"} offset 1d) / sum(deaths{state=\"$state\",county=\"$county\"}offset 1d) * 100"
    }
   ]
  },
  {
   "title": "% Change [3d] - Deaths",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{state=\"$state\",county=\"$county\"} - deaths{state=\"$state\",county=\"$county\"} offset 3d) / sum(deaths{state=\"$state\",county=\"$county\"}offset 3d) * 100"
    }
   ]
  },
  {
   "title": "State % of USA Deaths",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{state=\"$state\"})/sum(deaths{country=\"US\"}) * 100"
    }
   ]
  },
  {
   "title": "County % of Deaths USA",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{state=\"$state\", county=\"$county\"})/sum(deaths{country=\"US\"}) * 100"
    }
   ]
  },
  {
   "title": "Top Counties Reporting [confirmed]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum(confirmed{state=\"$state\"}) by (county))",
     "legendFormat": "{{county}}"
    }
   ]
  },
  {
   "title": "Top Counties Reporting [Deaths]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum(deaths{state=\"$state\"}) by (county))",
     "legendFormat": "{{county}}"
    }
   ]
  },
  {
   "title": "Top 10 US Counties  [Deaths]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum(deaths{country=\"US\"}) by (county))",
     "legendFormat": "{{county}}"
    }
   ]
  },
  {
   "title": "Top 10 US States  [Deaths]",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "topk(10, sum(deaths{country=\"US\"}) by (state))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Map [State, County]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "State View",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "valueName": "current",
   "targets": [
    {
     "expr": "confirmed{state=\"$state\", lat!=\"0.0\"} >0"
    }
   ]
  },
  {
   "title": "County View",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 11 },
   "valueName": "current",
   "targets": [
    {
     "expr": "confirmed{county=\"$county\"} >0"
    }
   ]
  },
  {
   "title": "State Confirmed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{state=\"$state\"})"
    }
   ]
  },
  {
   "title": "State Deaths",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\",state=\"$state\"})"
    }
   ]
  },
  {
   "title": "County Confirmed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\",state=\"$state\",county=\"$county\"})"
    }
   ]
  },
  {
   "title": "County Deaths",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\",state=\"$state\",county=\"$county\"})"
    }
   ]
  },
  {
   "title": "Coming Soon SCORE",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 19 },
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "title": "Coming Soon Score",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 19 },
   "targets": [
    { "expr": "0" }
   ]
  },
  { "title": "County Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  { "title": "State Trends - Forecast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } }
 ]
}