{
 "title": "USA Data [metrics]",
 "tags": [ "dash-3" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "US Confirmed Numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cases",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"})"
    }
   ]
  },
  {
   "title": "24HR  Increase",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"} - confirmed{country=\"US\"} offset 1d)"
    }
   ]
  },
  {
   "title": "[3 Day] Confirmed Increase",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"} - confirmed{country=\"US\"} offset 3d)"
    }
   ]
  },
  {
   "title": "1 Day %Change [Confirmed]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"} - confirmed{country=\"US\"} offset 1d) / sum(confirmed{country=\"US\"}offset 1d) * 100"
    }
   ]
  },
  {
   "title": "3 Day %Change [Confirmed]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"} - confirmed{country=\"US\"} offset 3d) / sum(confirmed{country=\"US\"}offset 3d) * 100"
    }
   ]
  },
  {
   "title": "7 Day % Change [Confirmed]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"} - confirmed{country=\"US\"} offset 7d) / sum(confirmed{country=\"US\"}offset 7d) * 100"
    }
   ]
  },
  {
   "title": "% of World Cases [Confirmed]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(confirmed{country=\"US\"}) / sum(confirmed) * 100"
    }
   ]
  },
  { "title": "US Death Numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Deaths",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"})"
    }
   ]
  },
  {
   "title": "24HR Increase",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"} - deaths{country=\"US\"} offset 1d)"
    }
   ]
  },
  {
   "title": "[3 day] Death Increase",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"} - deaths{country=\"US\"} offset 3d)"
    }
   ]
  },
  {
   "title": "1 Day %Change [Deaths]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"} - deaths{country=\"US\"} offset 1d) / sum(deaths{country=\"US\"}offset 1d) * 100"
    }
   ]
  },
  {
   "title": "3 Day %Change [Deaths]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"} - deaths{country=\"US\"} offset 3d) / sum(deaths{country=\"US\"}offset 3d) * 100"
    }
   ]
  },
  {
   "title": "CFR (Fatality Rate)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"}) / sum(confirmed{country=\"US\"}) * 100"
    }
   ]
  },
  {
   "title": "% of World Cases [Deaths]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(deaths{country=\"US\"}) / sum(deaths) * 100"
    }
   ]
  },
  {
   "title": "US Map(s) of Confirmed & Deaths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Cases in USA - by County",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "valueName": "current",
   "targets": [
    {
     "expr": "confirmed{country=\"US\", lat!=\"0.0\"} >0"
    }
   ]
  },
  {
   "title": "Deaths in USA - by County",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
   "valueName": "current",
   "targets": [
    {
     "expr": "deaths{country=\"US\", lat!=\"0.0\"} >0"
    }
   ]
  },
  {
   "title": "Top States and Counties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Confirmed (by US State)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "topk(10, sum(confirmed{country=\"US\"}) by (state))",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Top 10 Deaths (by US State)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 20 },
     "targets": [
      {
       "expr": "topk(10, sum(deaths{country=\"US\"}) by (state))",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Top 10 Confirmed (by US County)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "topk(10, sum(confirmed{country=\"US\"}) by (county, state))",
       "legendFormat": "{{county}},{{state}}"
      }
     ]
    },
    {
     "title": "Top 10 Deaths (by US County)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 28 },
     "targets": [
      {
       "expr": "topk(10, sum(deaths{country=\"US\"}) by (county, state))",
       "legendFormat": "{{county}},{{state}}"
      }
     ]
    },
    {
     "title": "Top 10 Delta:Cases (by State)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "topk(10, delta(confirmed{country=\"US\"}[1d]))",
       "legendFormat": "{{county}},{{state}}"
      }
     ]
    },
    {
     "title": "Top 10 Delta:Deaths (by State)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 36 },
     "targets": [
      {
       "expr": "topk(10, delta(deaths{country=\"US\"}[1d]))",
       "legendFormat": "{{county}},{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Changes in Confirmed & Deaths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "Linear Predictions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "7 days [from today] \"Confirmed\"",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(predict_linear(confirmed{country=\"US\"}[1d],168*3600))"
      }
     ]
    },
    {
     "title": "7 days [from today] \"Deaths\" ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
     "targets": [
      {
       "expr": "sum(predict_linear(deaths{country=\"US\"}[1d],168*3600))"
      }
     ]
    },
    {
     "title": "7 days [from today] \"Recovered\"",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(predict_linear(recovered{country=\"US\"}[1d],168*3600))"
      }
     ]
    },
    {
     "title": "14 days [from today] \"Confirmed\"",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(predict_linear(confirmed{country=\"US\"}[1d],366*3600))"
      }
     ]
    },
    {
     "title": "14 days [from today] \"Deaths\"",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
     "targets": [
      {
       "expr": "sum(predict_linear(deaths{country=\"US\"}[1d],366*3600))"
      }
     ]
    },
    {
     "title": "14 days [from today] \"Recovered\"",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(predict_linear(recovered{country=\"US\"}[1d],366*3600))"
      }
     ]
    }
   ]
  }
 ]
}